### ISSUE TITLE
Integrate NEUBIAS search into Fiji search bar

### ISSUE THREAD

**Issue by imagejan** [NeuBIAS/neubias-ijsearch#4]
This can essentially be achieved by migrating [`BISESearcher.java`](https://github.com/scijava/scijava-search/blob/14315f805141d18c71c712225cc8fbfde090cfa6/src/main/java/org/scijava/search/web/BISESearcher.java) from `scijava/scijava-search` and un-commenting the line containing the annotation:

https://github.com/scijava/scijava-search/blob/14315f805141d18c71c712225cc8fbfde090cfa6/src/main/java/org/scijava/search/web/BISESearcher.java#L57

The plugin will then be auto-discovered by the SciJava framework, and available in the search results.

**Comment by vcaldas** [comment]
Hi @imagejan  Thanks a lot for putting effort in the tool! 

I am having a issue when I try to compile the scijava-search.jar with the un-commented line. 
When I try to write in the search bar it says that ..

[ERROR] null
java.lang.IllegalArgumentException: Required service is missing: org.scijava.search.SearchService
Context: org.scijava.Context@332350e9
ClassLoader: java.net.URLClassLoader@14f3c6fc

and so on.
Am I missing something obvious here? Could you point to the info that would help me solving that? 
Cheers
Victor

**Comment by vcaldas** [comment]
Hi @imagejan . thanks a lot for the implementation.
I didn't manage to solve the issue with he <meta> so I propose a solution using Jsoup. https://gist.github.com/vcaldas/4f416f9cc13565a7a5d5088945aa838b

It works!
